name: Cypress Tests

on:
  push:
    branches:
      - main  # Isso faz com que os testes rodem apenas quando um push for feito na branch "main"

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # O sistema operacional onde os testes serão executados

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4  # Clona o código do teu repositório

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Garante que a versão do Node.js seja instalada corretamente

      - name: Instalar dependências
        run: npm install  # Instala todas as bibliotecas necessárias do teu projeto

      - name: Executar testes Cypress
        run: npx cypress run  # Executa os testes do Cypress automaticamente
